apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "48603787-7f9f-4c17-9071-677bcae61660"
      - op: replace
        path: /spec/parameters/tenantId
        value: "36e054ee-92ea-404f-97ee-2859b2462cd6"
