apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "2b36e208-a060-4a4b-8ba5-00bf7addb724"
      - op: replace
        path: /spec/parameters/tenantId
        value: "36e054ee-92ea-404f-97ee-2859b2462cd6"
  # ObjectStore patch commented out - CRD not available
  # - target:
  #     kind: ObjectStore
  #     name: customer1-objectstore
  #   patch: |-
  #     - op: replace
  #       path: /spec/configuration/destinationPath
  #       value: "https://alexmercurybackup.blob.core.windows.net/customer1"
  - target:
      kind: Cluster
      name: customer1-db
    patch: |-
      - op: replace
        path: /spec/backup/barmanObjectStore/destinationPath
        value: "https://alexmercurybackup.blob.core.windows.net/customer1"
