apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customer1
resources:
  - namespace.yaml
  - secrets.yaml
  #- objectstore.yaml
  #- database.yaml
  #- scheduled-backup.yaml
  - configmap.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
