apiVersion: v1
kind: ConfigMap
metadata:
  name: {{CUSTOMER_NAME}}-n8n-config
data:
  N8N_PORT: "3008"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  N8N_SECURE_COOKIE: "true"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "{{CUSTOMER_NAME}}-db-rw.{{CUSTOMER_NAME}}.svc.cluster.local"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "app"
