apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{CUSTOMER_NAME}}
resources:
  - namespace.yaml
  - secrets.yaml
  - database.yaml
  - configmap.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
