apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer3-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - customer3.mercury.kubetest.uk
      secretName: customer3-tls
  rules:
    - host: customer3.mercury.kubetest.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer3-n8n
                port:
                  number: 3008
