apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer3/
patches:
  - target:
      kind: SecretProviderClass
      name: customer3-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "49ff401d-772c-4e31-b711-f4e621375ed6"
      - op: replace
        path: /spec/parameters/tenantId
        value: "36e054ee-92ea-404f-97ee-2859b2462cd6"
